### ISSUE TITLE
比如EAX寄存器赋值为1，则整个REX寄存器也会被赋值为1

### ISSUE THREAD

**Issue by everettjf** [feicong/macbook_issues#32]
+ 印数：第1印
+ 位置：第191页第3行
+ 问题：比如EAX寄存器赋值为1，则整个REX寄存器也会被赋值为1
+ 建议：比如EAX寄存器赋值为1，则整个RAX寄存器也会被赋值为1（REX 改为RAX）

**Comment by feicong** [comment]
OK 已确认
